CREATE TABLE USUARIO(
    ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    TIPO CHAR(1) NOT NULL,
    IDENTIFICADOR VARCHAR(20),
    NOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    SENHA VARCHAR(30) NOT NULL,
    NIVELACESSO INT,
    TELEFONE1 VARCHAR(11)
);
--------------------------------------

CREATE TABLE AREA_INTERESSE(
    ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    AREA_INTERESSE VARCHAR(50)
  );
--------------------------------------
CREATE TABLE PROFESSOR_AREAINTERESSE(
    ID_PROFESSOR INT,
    ID_AREAINTERESSE INT,
    FOREIGN KEY(ID_PROFESSOR) REFERENCES USUARIO (ID),
    FOREIGN KEY(ID_AREAINTERESSE) REFERENCES AREA_INTERESSE (ID)
);
--------------------------------------

CREATE TABLE TEMA(
    ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    TEMA VARCHAR(50)
  );
--------------------------------------

CREATE TABLE PROFESSOR_TEMA(
    ID_PROFESSOR INT,
    ID_TEMA INT,
    FOREIGN KEY(ID_PROFESSOR) REFERENCES USUARIO (ID),
    FOREIGN KEY(ID_TEMA) REFERENCES TEMA (ID)
);
--------------------------------------

