/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dao.AlunoDAO;
import javax.swing.JOptionPane;
import sg.tcc.Aluno;

/**
 *
 * @author diogo.almeida
 */
public class jifCadastroAluno extends javax.swing.JInternalFrame {

    /**
     * Creates new form jifCadastroAluno
     */
    public jifCadastroAluno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtNomeAluno = new javax.swing.JTextField();
        jtMatriculaAluno = new javax.swing.JTextField();
        jtEmailAluno = new javax.swing.JTextField();
        jtTelefoneAluno = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setClosable(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastrar novo Aluno"));

        jLabel1.setText("Nome:");

        jLabel2.setText("Matricula:");

        jLabel3.setText("E-mail:");

        jLabel4.setText("Telefone:");

        jtNomeAluno.setToolTipText("");
        jtNomeAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtNomeAlunoActionPerformed(evt);
            }
        });

        jtMatriculaAluno.setToolTipText("");

        jtEmailAluno.setToolTipText("");

        jtTelefoneAluno.setToolTipText("");

        jButton1.setText("Cadastrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Limpar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtNomeAluno)
                            .addComponent(jtMatriculaAluno)
                            .addComponent(jtEmailAluno)
                            .addComponent(jtTelefoneAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtNomeAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtMatriculaAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtEmailAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtTelefoneAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(33, 33, 33))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        setBounds(250, 50, 447, 382);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jtNomeAluno.setText("");
        jtMatriculaAluno.setText("");
        jtEmailAluno.setText("");
        jtTelefoneAluno.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jtNomeAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtNomeAlunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtNomeAlunoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        // instanciando a classe Usuario do pacote modelo e criando seu objeto usuarios
        Aluno usuarios = new Aluno();
        usuarios.setNome(jtNomeAluno.getText());
        usuarios.setNrMatricula(jtMatriculaAluno.getText());
        usuarios.setEmail(jtEmailAluno.getText());
        usuarios.setTelefone(jtTelefoneAluno.getText());

        // fazendo a validação dos dados
        if ((jtNomeAluno.getText().isEmpty()) || (jtMatriculaAluno.getText().isEmpty()) || (jtEmailAluno.getText().isEmpty()) || (jtTelefoneAluno.getText().isEmpty()) || (jtTelefoneAluno.getText().isEmpty())) {
            JOptionPane.showMessageDialog(null, "Preencher todos os campos!");
        }
        else {

            // instanciando a classe UsuarioDAO do pacote dao e criando seu objeto dao
            AlunoDAO dao = new AlunoDAO();
            dao.create(usuarios);
            JOptionPane.showMessageDialog(null, "Aluno "+jtNomeAluno.getText()+" inserido com sucesso! ");
        }

        // apaga os dados preenchidos nos campos de texto
        jtNomeAluno.setText("");
        jtMatriculaAluno.setText("");
        jtEmailAluno.setText("");
        jtTelefoneAluno.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jtEmailAluno;
    private javax.swing.JTextField jtMatriculaAluno;
    private javax.swing.JTextField jtNomeAluno;
    private javax.swing.JTextField jtTelefoneAluno;
    // End of variables declaration//GEN-END:variables
}
